# -*- coding: utf-8 -*-
"""Clase 1-blank-2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zz-BTuRHoUtL7XHmsrF-K9VTJAZ1HbI4

# Python para análisis de datos


Para iniciar con python se recomienda instalar [ANACONDA](https://www.continuum.io/downloads) , en la version  3.x

---


**Nota** Despues de instalado se puede cambiar de version siguiendo los  [pasos](http://conda.pydata.org/docs/py2or3.html) , [ayuda](http://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook)
---

## Verifiquemos que tenemos lo que necesitamos


##Nombre: Yohana Delgado
##Se realiza solucion a cada uno de los puntos planteados.
"""

#@title
# Python version
import sys
print('Python: {}'.format(sys.version))

import sklearn
print('sklearn: {}'.format(sklearn.__version__))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

"""
## Buscar ayuda
Tenemos la opción de usar ? para ver la ayuda de una función, o usar tab para ver las funciones disponibles de un objeto

Ejercicio: importar la biblioteca random y buscar ayuda sobre la función `random`

"""

import random
help(random)

"""# Python
Python es un lenguaje de programación de alto nivel, interpretado, interactivo, orientado a objetos y de propósito general. Fue creado por Guido van Rossum durante 1985-1990. Al igual que Perl, el código fuente de Python también está disponible bajo la Licencia Pública General de GNU (GPL).

basado en [Complete Python Bootcamp: Go from zero to hero in Python 3](https://www.udemy.com/complete-python-bootcamp/) y [Python - Tutorial](https://www.tutorialspoint.com/python/index.htm) (*warning: is python2*)

- se considera la mejor práctica ([PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)) que los nombres de las variables están en minúsculas con guiones bajos
- Python utiliza *escritura dinámica*, lo que significa que puede reasignar variables a diferentes tipos de datos.
- Python soporta cuatro tipos numéricos diferentes

  - int (enteros con signo) `5`
  - long (enteros largos, también se pueden representar en octal y hexadecimal) `5L`,` 0x80`
  - float (valores reales de punto flotante) `0.0`,` 0.5e52`
  - complejo (números complejos) `14.5j`
- Se puede pensar en las listas de la versión más general de una secuencia en Python. A diferencia de las cadenas, son mutables, lo que significa que los elementos dentro de una lista se pueden cambiar.
- Lo importante de una lista es que los elementos de una lista no tienen que ser del mismo tipo.
- Una gran característica de las estructuras de datos de Python es que admiten el anidamiento. Esto significa que podemos tener estructuras de datos dentro de estructuras de datos
-En las estructuras de datos Diccionario([dict](https://docs.python.org/3/tutorial/datastructures.html)) Las claves son únicas dentro de un diccionario, mientras que los valores pueden no serlo.
- Los valores de un diccionario pueden ser de cualquier tipo, pero las claves deben ser de un tipo de datos inmutables como cadenas, números o tuplas.
- En Python, la TUPLA es otro tipo de arreglo que dispone el Python. Esta variable está más cerca al concepto matemático de vector, puesto que en Python la tupla se maneja como una lista más cerrada porque no puede cambiar elementos individuales, en otras palabras, es inmutable según lo definen [tuples](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences)


Un buen punto de partida es descargar un [datasheet] del tema de busqueda esta pagina presenta excelentes resumenes de python [Python Crash Course, Second Edition](https://ehmatthes.github.io/pcc_2e/cheat_sheets/cheat_sheets/), el cual es resumen de un muy buen [libro](https://nostarch.com/pythoncrashcourse2e)

## Python basico


Sin ejecutar el codigo, que crees que retorna cada item? pruebalo

1. **numbers** 

```
3/2 
#Resultado: 1.5

3/float(2)
#Resultado: 1.5

3%2
#Resultado:  1

3.00//2.00
#Resultado: 1.5

2**3
#Resultado: 8

4**0.5

#Resultado: 2
import math  ##Importa libreria
math.sqrt(4)
#Resultado: 2.0

2 + 10 * 10 + 3
#Resultado: 105

(2+10) * (10+3)
#Resultado: 156
```
2. **Variables**

```
a = 10
a =a + 
#Resultado: 20

a += 10
#Resultado: 30

b = c = 
#Resultado: a=30 , b=30 , c=30

a,b,c = 1,2,"john"

#Resultado:  a=1 b =2  c= "john"
my_dogs = 2 
my_dogs = ['Sammy', 'Frankie'] 

#Resultado: my_dogs cambia de tipo de dato y valor.

del my_dogs
#Resultado: elimina my_dogs

```
3. **string**

```
str = 'Hello World!'

print (str)         
#Imprime valor del string (Hello word"

print (str[0])       
#substring de la primera posicion del 
string  "H"

print (str[2:5])
#Substr del string de la posicion 2 a la 
5 "llo"  

print (str[2:])
#Substr del string de la posicion 2 
hasta el final "llo World!"

print (str * 2)
#Concatena dos veces el string (Hello 
World!Hello World!   

print (str + "TEST")
#Concatea "Hello Word! y TEST , sin 
espacios

str.upper()
#convierte la oracion en mayusculas 
"HELLO WORD!"

str.split()
#Realiza un split de la cadena , y lo 
convierte en un arreglo de dos posiciones

'Carlos: {}'.format(str)
#Formatea el String e insetrta dentro de 
los corchetes "Hello Word!"

print(" %s ,  %s" %(str,"I'm Carlos"))
# da formato , introduciendo donde esta 
el %s el valor de la cadena "Hello 
Word!" y "I'm Carlos"

print('I wrote %s programs today.' %3.75)
# Da formato , introduciondo el valor 3.
75 donde esta %s.

print('I wrote %d programs today.' %3.75)
# Da formato , introduciondo el valor
entero donde esta %d. En este caso 
tomaria 3 Usado para valores numericos enteros

print('I wrote %5.2f programs today.' %3.75)
#%f Es usado para formatear numeros
flotantes, se dfine la longitud. el 
resultado seria "I wrote 3.75 programs today"

print('First: %s, Second: %5.2f, Third: %r' %('hi!',3.1415,'bye!'))
#Imprime : "First: hi Second: 3.14, Third: 'bye!'"


print('The {2} {1} {0}'.format('fox','brown','quick'))
#Imprime "The quick brown fox"


print('First Object: {a}, Second Object: {b}, Third Object: {c}'.format(a=1,b='Two',c=12.3))
#Imprime "First Object: 1, Second Object: Two, Third Object: 12.3"


print('{0:8} | {1:9}'.format('Fruit', 'Quantity'))
#Imprime "Fruit    | Quantity "

print('{0:8} | {1:9}'.format('Apples', 3.))
#Imprime "Apples   |       3.0"

print('{0:8} | {1:9}'.format('Oranges', 10))
#Imprime "Oranges  |        10"

```

4. **Array list**

```
my_list = [1,2,3]
#Crea lista de tres valores

my_list = ['A string',23,100.232,0]
#Cambia la lista a una lista de valores mixtos. 

my_list + ['new item']
#Añade un valor a la lista , dejandolo 
en la ultima posicion : ['A string',23,
100.232,0,'new item'], sin embargo al no 
tener un valor =, no se cambia el valor 
actual de my_list. 

my_list = my_list +['new item']
#Añade un valor a la lista , dejandolo 
en la ultima posicion : ['A string',23,
100.232,0,'new item'], y agreda dicho valor a la lista actual. 

my_list.pop(0)
#elimina el primer valor de la lista
#: A string

my_list.pop(-1)
#elimina el ultimo valor de la lista
#"new item"

my_list.reverse()
#Muestra la lista inversa
#[0,100.232,23]

my_list.sort()
#Muestra la lista ordenada
#[0,23,100.232]

my_list * 2
#Duplica la 
#[0,23,100.232,0,23,100.232]


my_list=[]
#Inicializa la 

my_list=array()
#Convierte la lista en un arreglo

num_list = range(1, 101)
#asigna el valor range(1,100) a la variable num_list

print(num_list[49])
#Retorna Nulo , en python (none)

type(num_list)
#Verifica el tipo de dato, en este caso seria de clase range

len(num_list)
#Len permite saber el tamaño , en este caso es 100.

new_list = [0, 1, 2, 3, 4, 5, 6]
#Inicializa una lista 

new_list[2] = 2001;
#Asigna el valor 2001 en el indice 2 de la lista

new_list[2:5]
#Extrae los valores de la lista desde la posicion 
#2 hasta la 5

new_list[:3]
#Extrae los valores de la lista desde la posicion 
#0  hasta la 3

new_list[-2:]

#Extrae los valores de la lista desde 
#la posicion final -2, en este caso 
#tomaria 5 y 6


list_1 = [1,2]
#Se crea una lista con los valores 1 y 2

list_2 = [3, 4]
#Se crea una lista con los valores 3 y 4

list_1=list_1+list_2
#Se concatena las lista 1 y 2, y este es asignado 
#a la lista 1 

list_1.append(list_2)
#Se agrega a la lista 1, la lista 2.


[num*2 for num in list_1]
#Por cada elemento de la lista se multiplica por dos, 
#retornando : 2,4,6,8,[3,4,3,4]

lst_1=[1,2,3]
#Se crea una lista con los valores 1 , 2 y 3

lst_2=[4,5,6]
#Se crea una lista con los valores 4 , 5 y 6

lst_3=[7,8,9]
#Se crea una lista con los valores 7,8 y 9

matrix = [lst_1,lst_2,lst_3]
#Se crea una matriz con los valores de la lista
#queda : [[1,2,3],[4,5,6],[7,8,9]]

matrix[0][0]=8
#Se asigna a la posicion de la matrix [0,0] el valor 8
#[[8,2,3],[4,5,6],[7,8,9]]

print(matrix)
#Imprime la matrix

```
4.  **Dictionary**

```
d = {'a':10, 'b':20, 'c':30}
#Se crea un diccionario 

d['a']
#Obtenemos el valor de a que es 10

d['b']=40
#Se asigna a b el valor de 40

d.clear()
#Se limpia el dicionario y queda vacio {}

print(d)
#Imprimimos d 

dict = {'Name': 'Zara', 'Age': 7, 'Name': 'Manni'}
#Se crea un diccionario

dict.values()
#Obtenemos los valores (7 y Manni)

dict.keys()
#Obtenemos las llaves (Age y Name)

dict.items()
#Obtenemos todos los valores del diccionario

print(dict['Name'])
#Obtnemos el valor de Name que es Manni

dict2['Name']='Carlos'
#Se asigna el valor Carlos a la llave Name 
#del segundo diccionario, sin ambargo hay error
#Puesto que no se a inicializado el diccionario 

dict.update(dict2)
#Actualizamos el diccionarion 1 con los 
#valores del diccionario 2, pero existe error 
#porque no se ha creado el diccionario.


locations = {'Sinan': ['Baltimore', 'MD'], 'Brandon': ['Arlington', 'VA']}
print(locations['Brandon'][1])
#Imprime el valor "VA"

from numpy import random
data = {'a'+str(i) : random.randn() for i in range(7)}
print(data['a1'])
data

Crea un diccionario a partir de numeros random. 
```

5. ** functions**

```
def calc(a, b):
    return a + b
print(calc(2,3))
#Codigo para crear una funcion simple
#de suma, de dos valores , el resultado es 5

```

Para probar cualquiera de los códigos anteriores, simplemente copie el bloque de código en la celda de python a continuación.
"""

print('{0:8} | {1:9}'.format('Apples', 3.))

"""![numpy](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/640px-NumPy_logo.svg.png)


## Numpy


NumPy es el paquete fundamental para la computación científica con Python. Contiene entre otras cosas:

- un poderoso objeto de matriz N-dimensional

-funciones sofisticadas (de transmisión)

- herramientas para integrar código C / C ++ y Fortran

- Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios


Todo Arreglo/array en Numpy es tratado como un objeto que entre sus propiedades tiene:

- ndarray.ndim –> Proporciona el número de dimensiones de nuestro array. El array identidad es un array cuadrado con una diagonal principal unitaria.
- ndarray.shape –> Devuelve la dimensión del array, es decir, una tupla de enteros indicando el tamaño del array en cada dimensión. Para una matriz de n filas y m columnas obtendremos (n,m).
- ndarray.size –> Es el número total de elementos del array.
- ndarray.dtype –> Es un objeto que describe el tipo de elementos del array.
- ndarray.itemsize –> devuelve el tamaño del array en bytes.
- ndarray.data –> El buffer contiene los elementos actuales del array.

## Creación de Arrays


- identity(n,dtype). Devuelve la matriz identidad, es decir, uma matriz cuadrada nula excepto en su diagonal principal que es unitaria. n es el número de filas (y columnas) que tendrá la matriz y dtype es el tipo de dato. Este argumento es opcional. Si no se establece, se toma por defecto como flotante.
- ones(shape,dtype). Crea un array de unos compuesto de shape elementos.
- zeros(shape, dtype). Crea un array de ceros compuesto de “shape” elementos”.
- empty(shape, dtype). Crea un array de ceros compuesto de “shape” elementos” sin entradas.
- eye(N, M, k, dtype). Crea un array bidimensional con unos en la diagonal k y ceros en el resto. Es similar a identity. Todos los argumentos son opcionales. N es el número de filas, M el de columnas y k es el índice de la diagonal. Cuando k=0 nos referimos a la diagonal principal y por tanto eye es similar a identity.
- arange([start,]stop[,step,],dtype=None). Crea un array con valores distanciados step entre el valor inicial star y el valor final stop. Si no se establece step python establecerá uno por defecto.
- linspace(start,stop,num,endpoint=True,retstep=False). Crea un array con valor inicial start, valor final stop y num elementos.
- meshgrid(x,y). Genera una matriz de coordenadas a partir de dos los arrays x, y.

## Funciones

El módulo numpy contiene todas las operaciones usuales entre arrays como las matemáticas (suma, resta, multiplicación, etc), las lógicas (and, or, xor, etc), binarias, ... 
[Operaciones Numpy](https://drive.google.com/file/d/17wZqpCvckCb8Ous3HAaRqPu33rJKtTeB/view?usp=sharing)


[buen tutorial](http://pendientedemigracion.ucm.es/info/aocg/python/modulos_cientificos/numpy/index.html)

Lo más fácil y sencillo es en caso de duda consultar la documentación oficial. [documentacion](https://docs.scipy.org/doc/numpy/reference/index.html#reference)



"""

import numpy as np # Importamos numpy como el alias np

# tipo de datos
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
#funciones basicas
miArray = np.arange(10) # Creamos un array de 0 a 9 separados de uno en uno
print (miArray) # Presentamos en pantalla el array creado
print (type(miArray))   #Comprobamos que es un ndarray
print (miArray.ndim )   # Consultamos el número de dimensiones
print (miArray.shape )  # Consultamos la dimensión
print (miArray.size )  # Consultamos la dimensión
print (miArray.dtype )  # Consultamos el tipo de elementos del array
print (miArray.itemsize )  # tamaño en bytes
print (miArray.data )  # Consultamos el buffer de memoria.

# array bidimensionales
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])

print(arr2d[0][2])
#arr2d[0,2]

#grupo de elementos
print((arr2d[:,1]))

# acesso con operaciones
print(arr2d[arr2d>4])

#fancy indexing (una matrix es en verdad un arreglo)
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

#seleccionar columnas en desorden
print (arr[[4, 3, 0, 6]])
#Using negative indices select rows from the end
print(arr[[-3, -5, -7]])

#reorganizar vectores
arr = np.arange(32).reshape((8, 4))
print(arr)

"""### **Ejercicio**

Crear dos vectores de diez numeros aleatorios enteros [np.random.randint](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html) entre 1 y 10 y realizar las siguientes operaciones:





"""
import numpy as np

array1=np.random.randint(10, size=10) # Arreglo 1
array1=np.array(array1)
array2=np.random.randint(10, size=10) # Arreglo 2
array2=np.array(array2)

print('Array1=')
print(array1)
print('Array2=')
print(array2)
#- sumarlos
sumarray=array1+array2
print(sumarray)

#- concatenar los dos arreglos
concarray = np.concatenate((array1, array2), axis=0)
print(concarray)

#- encontrar la sumatoria de los valores
totalarray = array1.sum()  +  array2.sum()
print(totalarray)

#- encontrar la media de los valores
mediaarray1=np.mean(array1) #Media arreglo 1
mediaarray2=np.mean(array2) #Media arreglo 2

print('Media array 1 . ' + str(mediaarray1) )
print('Media array 2 . ' + str(mediaarray2) )

print('Media concatenacion:' + str(np.mean(concarray)))

#- imprimir los numeros mayores que 5
print("Números mayores que 5 en los arreglos son: " + str(concarray[concarray>5]))

   

##recorrer el arreglo en busqueda de los mismos valores
# determinar las posiciones de los numeros que son iguales en los arreglos



print(array1[array1==array2])


##recorrer el arreglo en busqueda de los mismos valores
pos1=0;

for i in array1:
    
    pos2=0;
    for x in array2:
        if(i==x):
            print ('El Número ' + str(x) + ' esta en la posición '+ str(pos1) + ' del arreglo 1 y en la posición ' + str(pos2)+ ' del arreglo 2\n')
        pos2+=1;
    pos1+=1;

"""## SQLite

Cuando abre un excel o CSV en Python y lo asigna a un nombre de variable, está usando la memoria de su computadora para guardar esa variable. Acceder a los datos desde una base de datos como SQL no solo es más eficiente, sino que también le permite importar solo las partes de los datos que necesita.


Cada una de las bases de datos tienen sus librerias para python, a manera de ejemplo veamos SQLite.

- Revisar la base de datos en linea [sqliteonline](https://sqliteonline.com/)


- **Ejercicio** escribamos tres query (enunciado en [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) y luego el codigo sql respectivo.

los datos son   la Guía de valor para vehículos en Colombia suministrada por fasecolda, que se puede descargar de [Kaggle](https://www.kaggle.com/panchicore/vehicles-colombia-fasecolda/version/1)


[Link de descarga](https://drive.google.com/file/d/1wVSVbq1cJ68dU-0D8c4tPh83Hjy8azPM/view?usp=sharing)


tutorial [sqllite](http://www.datacarpentry.org/python-ecology-lesson/08-working-with-sql) 

"""

# Cargamos el archivo (solo en collaborative) en caso contrario colocar el archivo en la raiz
#from google.colab import files
#files.upload()

import sqlite3

# Create a SQL connection to our SQLite database
con = sqlite3.connect("guia_fasecolda.sqlite")

cur = con.cursor()

# the result of a "cursor.execute" can be iterated over by row
i=0;
for row in cur.execute('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0  LIMIT 10;'):
    print(row)
    

#AQUI Realize sus consultas sql de los datos
print('\nEjercicios SQL\n')
print('Ejercicios 1\n')
for row in cur.execute('SELECT marca,clase, count(1) as cantidad FROM carros  where marca="MAZDA" group by clase, marca ;'):
    print(row)

print('\nEjercicios 2\n')
for row in cur.execute('SELECT max(capacidadpasajeros) maximo_pasajeros, clase FROM carros group by clase;'):
    print(row)
    
    
print('\nEjercicios 3\n')
for row in cur.execute('SELECT max(capacidadcarga) maxima_capacidadcarga, min(capacidadcarga) minima_capacidadcarga, clase FROM carros group by clase;'):
    print(row)
    
    
#Be sure to close the connection.
con.close()

"""## Pandas

![Panda Logo](https://pandas.pydata.org/_static/pandas_logo.png)

Documentación de [Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html)

Pandas es una librería para el análisis de datos que cuenta con las estructuras de datos que necesitamos para limpiar los datos en bruto y que sean aptos para el análisis (por ejemplo, tablas). Es importante señalar aquí que, dado que pandas lleva a cabo tareas importantes, como alinear datos para su comparación, fusionar conjuntos de datos, gestión de datos perdidos, etc., se ha convertido en una librería muy importante para procesar datos a alto nivel en Python (es decir, estadísticas ). Pandas fue diseñada originalmente para gestionar datos financieros, y como alternativa al uso de hojas de cálculo (es decir, Microsoft Excel). Esta libreria tambien es equivalente en gran parte a las estructuras de datos de R.

La estructura de datos básica de pandas son:

- **Series**: Son arrays unidimensionales con indexación (arrays con índice o etiquetados), similar a los diccionarios. Pueden generarse a partir de diccionarios o de listas.
- **DataFrame**: Es una colección ordenada de columnas con nombres y tipos. Son estructuras de datos similares a las tablas de bases de datos relacionales como SQL, donde una sola fila representa un único caso (ejemplo) y las columnas representan atributos particulares. 
- **Panel, Panel4D y PanelND**: Estas estructuras de datos permiten trabajar con más de dos dimensiones. 

Sobre este tipo de estructura de datos se aplican funciones, ejemplo:

"""

print('\nData frames\n')
import pandas as pd

dates = pd.date_range('20200101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

#valores iniciales de la lista
df.head()

#valores finales de la lista
df.tail(3)

#aceder a los datos como un arreglo numpy
print(df.index)
print(df.columns)
df.values

# acediendo ciertos datos
df['A']
df[1:3]
df[df.A > 0]

df.sort_values(by='B')

# toda la estadistica descriptiva

df.describe()

"""Existen herramientas que permiten generar una descripción grafica y numerica automaticamente tales como:
- [sweetviz](https://github.com/fbdesignpro/sweetviz)
- [pandas profiling](https://github.com/pandas-profiling/pandas-profiling)

Estas librerias no estan por defecto instaladas en google colab o en su ambiente de trabajo, por lo cual se pueden instalar con 

  *!pip install package*
"""

#pip install sweetviz

import sweetviz as sv

my_report = sv.analyze(df)
my_report.show_notebook()

#pip install pandas-profiling==2.9.0

from pandas_profiling import ProfileReport
profile = ProfileReport(df)
profile.to_widgets()

"""## Comprender los datos con estadísticas descriptivas
Una vez que haya cargado sus datos en Python, debe poder entenderlos. Cuanto mejor pueda comprender sus datos, mejores y más precisos serán los modelos que puede construir.
El primer paso para comprender sus datos es utilizar estadísticas descriptivas. 

### **Ejercicio**

- Realize un query sobre los datos que desea analizar con datos de precios de varios años
- Revise la distribución de sus datos con la función [describe()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.describe.html#pandas.DataFrame.describe).
- Calcule la correlación por pares entre sus variables usando la función [corr ()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.corr.html#pandas.DataFrame.corr) .

[documentación](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)




"""

import pandas as pd
import sqlite3
from IPython.display import display, HTML

# Read sqlite query results into a pandas DataFrame
con = sqlite3.connect("guia_fasecolda.sqlite")

#ESCRIBE LA CONSULTA DE LO QUE DESEAS ANALIZAR
#df = pd.read_sql_query('SELECT Marca,Referencia1,Cilindraje,Peso,"2015","2016","2017" FROM carros where Cilindraje<1500 AND Cilindraje>1200 AND "2015">0;', con)
df = pd.read_sql_query('SELECT * FROM carros', con)


print("Total de memoria ram requerida ",df.memory_usage().sum())

#estadistica descriptiva
display(HTML(df.describe().to_html()))
#correlación entre las columnas
display(HTML(df.corr().to_html()))

con.close()

"""Como notaste en el ejemplo anterior Pandas permite conectarse directamente a la base de datos, tambien permite leer datos en multiples formatos [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) , por ejemplo si yo quiero cargar los datos originales de FASECOLDA"""

# Cargamos el archivo (solo en collaborative)
#from google.colab import files
#files.upload()

data = pd.read_csv('guia_fasecolda.csv')
print("Total de memoria ram requerida ",data.memory_usage().sum())


print(data.columns)

"""## Comprender los datos con visualización

Debes dedicar tiempo a comprender mejor tus datos. Una segunda forma de mejorar su comprensión de sus datos es mediante el uso de técnicas de visualización de datos . Usar la representación en Python para comprender los atributos por sí solos y sus interacciones. Ejemplos:
- Use la función hist () para crear un histograma de cada atributo.
- Use la función plot (kind = 'box') para crear diagramas de caja y cajas de cada atributo.
- Utilice la función  pandas.scatter_matrix() para crear gráficos de dispersión por pares de todos los atributos.

Es importante agregar```% inline matplotlib```  en la primera línea de su código si desea que la imagen esté incrustada en el *notebook* de Júpiter.


[pyplot](http://matplotlib.org/api/pyplot_api.html) es la mejor opción, claro que si trabajamos con Pandas, el tiene ya programada las graficas utlizando toda la información del dataset [ejemplo](https://pandas.pydata.org/pandas-docs/stable/10min.html#plotting)

### **Ejercicio** 

- Cargar el dataset de Fasecolda suministrado en csv

-  Comprenda sus datos usando la función `columns` para ver las filas
-  Utilize diferentes criterios para filtrar los datos.
-  utilize por lo menos tres funciones de pandas para describir los datos filtrados
-  Guarde los datos filtrados
-  Realize por lo menos tres graficas de los datos

[Link de descarga](https://drive.google.com/file/d/1mPnVLno8uLF1bD1EQbIRVUmxk1c1BVc4/view?usp=sharing)
"""

# Load CSV using Pandas from URL
import pandas as pd
import missingno as msno
from IPython.display import display, HTML
data = pd.read_csv('guia_fasecolda.csv')

print(data.columns)


#Realiza diferentes filtros sobre los datos y describelos
print('Describiendo los datos') 
print(data.info())
print(data.describe())
print(data.head())


print('accediendo a los datos')
##filtrar datos por marca
print(data[data.Marca=='MAZDA'])

##verificando tipos de novedad

print (data['Novedad'].unique()) # Se tiene 3 unicos valores de novedad M , A Y N , por tanto puede clasificar como categorico

print(data['Marca'].unique())#Se tiene gran variadedad de marcas, por tanto se realizara un onteo de las diferentes marcas que hay
#print(df[data['Estado']=='Activo'])
print (data['Estado'].unique())
print (data['Servicio'].unique())



data=data[data['Servicio']=='Publico']
print(data['Marca'].unique())
data=data[(data['Marca']=='MAZDA') | (data['Marca']=='APOLO') | (data['Marca']=='KIA')]

atributos = ['Novedad', 'Marca', 'Clase', 
          'Peso', 
        'Importado', 'Potencia', 'Cilindraje', 'CapacidadPasajeros', 
        'CapacidadCarga','Estado'] 
dataset=data[atributos] #Se tendran en cuenta solo los atributos de la lista 


import matplotlib.pyplot as plt
import seaborn as sns
color = '#0f4b78'
dataset.plot(kind='box', subplots=True, layout=(5,4), sharex=False, sharey=False, figsize=(14,14), 
                                        title='Gráfico de bigotes para cada atributo')
plt.savefig('shopping_box')
plt.show()


plt.figure(figsize=(12,8))
sns.heatmap(dataset.describe()[1:].transpose(),
            annot=True,linecolor="#0f4b78",
            linewidth=2,cmap=sns.color_palette("muted"))
plt.title("Resumen de atributos")
plt.show()

# Histogramas 
dataset.hist(bins=30, figsize=(14, 14), color='blue')

plt.suptitle("Histograma para cada atributo", fontsize=10)
plt.savefig('shopping_hist')
plt.show()



display(HTML((data.head().to_html())))


# Commented out IPython magic to ensure Python compatibility.

# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

plt.figure()
data[['Cilindraje','Peso']].plot(kind = 'box',ylim=(-1000,10000))
plt.title('mi primera grafica')


"""## Conclusiones

De acuerdo a este análisis previo de los datos sobre la base de datos de FASECOLDA, que preguntas harias de análisis de datos que puedan generar valor.
##¿que tipo de vehiculo es el que tiene mayor ingreso en el pais?
##¿Cuales son las marcas con mayor participacion y mayor accidentalidad?

Con que otra base de datos trabajarias para obtener valor de estos datos.

## Con una base de datos de ventas Automotriz y su referencia

Utilize por lo menos dos análisis del curso de estadistica y/o de visualización de datos para este problema.

Analisis Diagnostico:
 Revisar el comportamiento de las ventas de los vehiculos para realizar proyecciones de accidentalidad segun la marca
 
 Analitica Predictiva:
 
 Se podria realizar un modelo de vehiculos con mayor accidentalidad y hacer campañas de prevencion o aumentar el costo de los seguros para los mismos.


Plantea una pregunta aprendizaje supervisado y otra de supervisado que pensarias genere valor sobre este dataset

¿Puede estimarse accidentalidad de un vehiculo por marca y modelo para toma de decisiones?
¿Con el apoyo de herramientas  de busqueda "noticias" puede clasificarse las marcas con mayor indice de accidentes en el sector automotriz?
"""

           
